### ISSUE TITLE
Possibly implement invoke trap

### ISSUE THREAD

**Issue by Benvie** [tvcutsem/harmony-reflect#14]
This is only possible to do in SpiderMonkey but it still may be worth doing.

```js
var proxy = new Proxy({}, {});
proxy.method();
```
Will cause the following

1.) `proxy.[[Get]]('method')`, returns undefined
2.) `proxy.[[Get]]('__noSuchMethod__')`

If you implement the `get` trap to check for '__noSuchMethod__' that can be reflected as the invoke trap.

**Comment by tvcutsem** [comment]
Closing this issue as `invoke` is no longer part of ES6.
