### ISSUE TITLE
"illegal access" when using JSON.stringify on a Proxy

### ISSUE THREAD

**Issue by yelworc** [tvcutsem/harmony-reflect#38]
I am getting a strange error when trying to stringify a Proxy object in node.js: 

```
$ node --harmony
> var hr = require('harmony-reflect');
undefined
> JSON.stringify(new Proxy({}, {}));
illegal access
```

Just the plain string `illegal access` is thrown (not an `Error` object). Tested with node.js v0.10.26 and v0.11.13, same behavior.

**Comment by mschipperheyn** [comment]
I used harmony-reflect and harmony-proxy to get all working correctly

**Comment by tonylukasavage** [comment]
Wow, thanks for the `toJSON` trick! Really helped me out!
