### ISSUE TITLE
Not working with react-native

### ISSUE THREAD

**Issue by brysgo** [tvcutsem/harmony-reflect#47]
I haven't figured out why yet, but requiring 'harmony-reflect' in react-native is giving me "SyntaxError: Unexpected end of script".

I am using harmony and the Proxy object is present.

**Comment by tvcutsem** [comment]
I think I see what's going on. react-native concatenates all the files, but is not robust against the last line of a file containing a comment. You can see the concatenated files by navigating to <http://localhost:8081/index.ios.bundle> (react-native put a closing `})` after my comment)

Simply adding a newline at the end of your node_modules/harmony_reflect/reflect.js solves the issue.

I'll update my code and add the newline, even though this is really a concatenation issue of react-native.

Thanks for reporting!

**Comment by brysgo** [comment]
thanks!
