### ISSUE TITLE
Patches list in comments is not up-to-date

### ISSUE THREAD

**Issue by RReverser** [tvcutsem/harmony-reflect#54]
As commented in #50, `// Patches:` section in comments does not include:
* `defineProperty`
* `defineProperties`
* `getPrototypeOf`
* `getOwnPropertyNames`
* `setPrototypeOf`
* (maybe others, I used simple regex to find those)

**Comment by tvcutsem** [comment]
Thanks, I updated the list and also synchronized it with the list shown in the README.
