### ISSUE TITLE
Es6 Classes: Class constructors cannot be invoked without 'new' 

### ISSUE THREAD

**Issue by thetutlage** [tvcutsem/harmony-reflect#55]
Es6 Classes: Class constructors cannot be invoked without 'new'  try following

```javascript

  "use strict"

  var Reflect = require('harmony-reflect');

  class UsersController{

    constructor(name){
      this.name = name
    }

    hello(){
      return this.name
    }

  }

  var obj = Reflect.construct(UsersController, ["somename"])

  console.log(obj.hello())
```

**Comment by tvcutsem** [comment]
What ES6 environment are you using? I have tested your example using the ES6-to-ES5 translation of [BabelJS](https://babeljs.io/repl/) (both default and "high compliancy") and v1.3.0 of this library, and that all seems to work fine.

**Comment by thetutlage** [comment]
Using  iojs-v2.2.1

**Comment by zloirock** [comment]
Native classes, like native constructors, [can't be called w/o `new`](https://github.com/tvcutsem/harmony-reflect/blob/master/reflect.js#L1975-L1976). See this [post](http://www.2ality.com/2015/02/es6-classes-final.html). [Babel uses for this case `.bind`](https://goo.gl/Z2uLpM), but it creates problems with third arguments, for this reason I also not fixed it in [`core-js`](https://github.com/zloirock/core-js).

**Comment by thetutlage** [comment]
Yes , that is a handy trick :+1:
