### ISSUE TITLE
Reflect.Loader

### ISSUE THREAD

**Issue by monolithed** [tvcutsem/harmony-reflect#58]
Are there any plans to implement the one? )
http://whatwg.github.io/loader/

**Comment by tvcutsem** [comment]
Valid question, but I'm afraid Reflect.Loader is out of scope for this library. ES6 Module support is a big ticket item and this library does not intend to shim it. There's a dedicated library if you need it: https://github.com/ModuleLoader/es6-module-loader

**Comment by monolithed** [comment]
I got it, thanks
