### ISSUE TITLE
Incompatible with Edge browser

### ISSUE THREAD

**Issue by acterhd** [tvcutsem/harmony-reflect#59]
I'm tested with reflect.js Edge browser, but native Proxy stop working.

**Comment by tvcutsem** [comment]
Can you provide a little more information about what behavior you are observing and what behavior you were expecting instead?

Do you mean that after loading this library, the browser's native Proxy object is shadowed/inaccessible? How did you test for that?

**Comment by acterhd** [comment]
I read code, and see that you are replace "Proxy" object to empty function. But this is not good for edge.

**Comment by tvcutsem** [comment]
I see what you mean. I will add a feature-test that leaves the Proxy object
untouched if the new API is already implemented.

2015-08-25 18:31 GMT+02:00 acterhd <notifications@github.com>:

**Comment by tvcutsem** [comment]
Should be fixed in v1.4.2. The original `Proxy` object should be left untouched.

Let me know if you encounter any further issues.
