### ISSUE TITLE
Question: Does this work with IE11?

### ISSUE THREAD

**Issue by AlexGalays** [tvcutsem/harmony-reflect#78]
The lib hasn't be maintained for one year and yet it appears to be the most complete proxy shim implementation around (especially when it comes to supporting Arrays)

Would it work with IE11 or any browser that have neither kind of Proxies built in? It doesn't look like it.

**Comment by tvcutsem** [comment]
There are two parts to this shim: providing support for the `Reflect` and the `Proxy` ES6 built-ins. Shimming `Reflect` should work on IE11. Shimming `Proxy` requires a minimum amount of pre-ES6 Proxy support. Only older versions of Firefox, Chrome and nodejs provided support for this, so unfortunately shimming `Proxy` on IE11 is not possible.

**Comment by AlexGalays** [comment]
Thanks for the answer!
