### ISSUE TITLE
Conflict with `reflect-metadata`

### ISSUE THREAD

**Issue by sanex3339** [tvcutsem/harmony-reflect#79]
Hi. This package is using in different packages and plugins, for example here:
https://github.com/evilebottnawi/favicons (plugin https://github.com/jantimon/favicons-webpack-plugin)

When `favicons-webpack-plugin` plugin was loaded alongside with my plugin which using `reflect-metadata` - my plugin stopped working because of different API between `harmony-reflect` and `reflect-metadata`.

So, can you fix this from your side?

**Comment by tvcutsem** [comment]
Hi,

Did you find any workaround for your issue?

Currently the harmony-reflect module will always override the Reflect global. I could test if the Reflect global exists and if so, override or add methods on the existing Reflect global rather than replacing it. Do you think that would solve your issue?

**Comment by sanex3339** [comment]
I think that add methods (without overriding if possible) - best option.

**Comment by tvcutsem** [comment]
If I don't override the pre-existing methods then this library will not work anymore. This library implements a shim for Proxy objects. The patched Reflect methods need to recognize the shimmed Proxy objects generated by this library.

I'm unfamiliar with reflect-metadata, but at first glance, it seems it defines a different set of methods on its Reflect object. If that is the case, there won't be a conflict.

**Comment by tvcutsem** [comment]
Can you try upgrading to v1.6.0 (just released) and see if this solves your problem?

Relevant commit:
https://github.com/tvcutsem/harmony-reflect/commit/a79500fcd9af84948974d71e9dc04fbc48251fb6

**Comment by sanex3339** [comment]
It working now, thank you!

**Comment by tvcutsem** [comment]
glad to hear it works!
