### ISSUE TITLE
What is the actual license of this package?

### ISSUE THREAD

**Issue by VPenkov** [tvcutsem/harmony-reflect#80]
Hi,
The package.json file specifies `Apache-2.0 OR MPL-1.1`, and the LICENSE file says it's both of them (`This code is dual-licensed under both the Apache License and the MPL`).

Which one is valid?
I would assume that most people think it's *either* instead of *both* (like package.json specifies) because [this is how the NPM page displays it](https://www.npmjs.com/package/harmony-reflect). Any clarification would be appreciated.

**Comment by tvcutsem** [comment]
Yes, the intent is that it's either Apache or MPL, to give maximum flexibility of choice to users of this library.

**Comment by tvcutsem** [comment]
I clarified the wording in the `LICENSE` file. Hope this removes any remaining confusion. Cheers.
