### ISSUE TITLE
Reflect.construct incorrectly calls newTarget, causing infinite loops

### ISSUE THREAD

**Issue by loganfsmyth** [tvcutsem/harmony-reflect#81]
Came across this in https://stackoverflow.com/questions/52152988/how-to-avoid-stack-overflow-with-es-error-class caused by https://github.com/tvcutsem/harmony-reflect/blob/1e3e37f9b374a2c22fe5f698fadce432008faf55/reflect.js#L2086 using `newTarget` instead of `target`.

`Reflect.construct` is meant to call `target`. `newTarget` is pretty much just passed in to provide the prototype object for the newly constructed object, it should not be called.

**Comment by tvcutsem** [comment]
You are right: if `newTarget` is different from `target`, we still need to call `target`, just with a custom instance. Unfortunately the `newTarget` option cannot be perfectly emulated in pure ES5 as there is no way to pass a custom `newTarget` to the [[Construct]] internal method of a function (well, the only way to do that is through `Reflect.construct` in ES6, but that's the precisely the method we are shimming)

I patched the method to continue to use the bound function approach when `newTarget` is not set (or is equal to `target`). The advantage being that this approach will work even if `target` is an ES6 class constructor function.

If `newTarget` is set, then we fall back to creating a custom instance and calling the target's [[Call]] internal method with the custom instance. This works for plain constructor functions, but will fail for ES6 class constructors as they must be invoked using the `new` operator.

Thanks for reporting!
