### ISSUE TITLE
Index not found

### ISSUE THREAD

**Issue by vicasas** [tvcutsem/harmony-reflect#83]
- [x] The issue is present in the latest release.

When creating a `jsconfig.json` file I get the error

> File '/home/myproject/node_modules/harmony-reflect/index' not found.
> The file is in the program because:
> Root file specified for compilationts

**Comment by vicasas** [comment]
I reopened editor and the problem was solved.

**Comment by mpizzaca** [comment]
I am getting this same issue. Reopning the editor works temporarily but the issue comes back.

**Comment by vicasas** [comment]
@mpizzaca Exactly. It looks like a vscode error in reading the file.

**Comment by tvcutsem** [comment]
I tried reproducing this by upgrading to latest vscode, creating an empty new project directory, creating a `jsconfig.json` file and npm installing the latest harmony-reflect package. When creating new JS source files in this project, I don't see any error. Can you reproduce your problem in a minimal project setup?

Also, have you excluded your "node_modules" directory from your jsconfig file [as recommended in the vscode docs](https://code.visualstudio.com/docs/languages/jsconfig#_best-practices)? See https://code.visualstudio.com/docs/languages/jsconfig#_using-the-exclude-property for how to do this.

As I understand it, `jsconfig.json` is meant to create a JS project context in vscode. Files from installed packages under `node_modules` should not be treated as part of your own project codebase.

**Comment by mpizzaca** [comment]
Having trouble reproducing it as it seems to pop up only after some time. I suspect excluding node_modules will resolve it, thanks for that.

I noticed other repos using `"typings": "index.d.ts"` vs `"typings": "index"` in package.json - this might be confusing VSCode?

**Comment by tvcutsem** [comment]
Good remark about the "typings" field. I suspect that may indeed be the issue if other modules are not causing this problem. I will update the typings field accordingly.

**Comment by tvcutsem** [comment]
I released v1.6.2 with a fix. Closing this issue. Let me know if neither this fix nor excluding the package from jsconfig.json solves the problem.

**Comment by vicasas** [comment]
When updating to the new version at the moment there is no problem. Thanks.
